import type { Metadata } from "next";
import { Suspense } from "react";
import AuthNav from "./components/AuthNav";
import AppShell from "./components/AppShell";
import BrowseLink from "./components/BrowseLink";
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full">
        <Providers>
          <AppShell>
            <header className="border-b border-zinc-200 bg-white">
              <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
                <BrowseLink className="text-sm font-semibold">Templates</BrowseLink>
                <nav className="flex items-center gap-4 text-sm text-zinc-600">
                  <BrowseLink className="hover:text-black">Browse</BrowseLink>
                  <Suspense fallback={<div className="h-5 w-20 animate-pulse rounded bg-zinc-200" />}>
                    <AuthNav />
                  </Suspense>
                </nav>
              </div>
            </header>
            {children}
            {modal}
          </AppShell>
        </Providers>
      </body>
    </html>
  );
}
