import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthNav from "./components/AuthNav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-zinc-200 bg-white">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <a href="/" className="text-sm font-semibold">Templates</a>
            <nav className="flex items-center gap-4 text-sm text-zinc-600">
              <a href="/" className="hover:text-black">Browse</a>
              <AuthNav />
            </nav>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
